### PR TITLE
Refactor code and fix issues

### LINKED ISSUE #15: Comments from SJ Regarding 5/4/20 Version
1) There's a large gap between the address bar and the accordion that is especially prominent on mobile. (Is this caused by the address auto complete popup?) 2) The border separating items in the 3rd sub level of the accordion are the same color as the borders in the second level (the site names) so to me that makes it hard to tell that the 3rd level items are all part of the same record (site). Perhaps use a lighter border or eliminate the border altogether in the 3rd level. 3) In mobile the 3rd level text is very right-justified to the point where it almost impossible to read when the text is long.

### PR DESCRIPTION
**Pull request by ychoy**
@danekolsen  rewrote the front end for this app from scratch.  
Major changes:
   -Removed all Codyhouse code
   -Created new accordion menu from scratch using jQuery for functionality(cleaner than Bootstrap)
   -All outstanding Github issues except accessibility check should be fixed
   -Added a makeshift tablet layout to the code since the design didn’t include one
   -Reorganized image folder for ease of use
   -Organized just about all styles away from inline and into a SASS file for easier style changes in the future
   -Removed the accordion menu logic from index.html and put it in it’s own file setAccordion.js for modularization
   -Changed the location detail accordion menu section to match what was in Figma
- Fixes #15

### CODE REVIEW

**Comment by ychoy** [comment]
@danekolsen 

- Can you update `index.html` so the new footer background colors are in sync with the current file? I darkened the color to address accessibility (the color previously provided on design doesn't meet WCAG AAA standards for high enough color contrast). 
- Can you also add "results" next to the number (to match the user-friendly label revisions in Figma on the “Results” page)
- In the Figma Results page it looks like the miles is not included. I understand how that may be important information, so maybe it could be a separate line underneath the Details or below the Address. "Distance From Your Address" might be the label? @jliekim thoughts? 
- The color contrast is not high enough for the current background of the Results. Change it to `#006075`. It will match the buttons in the footer. 

@jliekim will you be uploading the hi-res version of the watermark images in an issue, or directly into this branch > assets > img?

**Comment by ychoy** [comment]
@danekolsen Thank you for taking on the work on refactoring this project. 
Great work cleaning up the code! It is much easier to read and maintain now 👍 

Can you also address the following issues?

- [ ] - Add `.gitignore`. Otherwise, `.DS_Store` will continue to be committed accidentally into the files. Inside gitignore please include .DS_Store, assets/img/.DS_Store and assets/.DS_Store.
- [ ] - Add this back into `index.html`. It's already in the current file, but got removed in this branch: ```<meta name="Description" content="A lookup tool for Santa Clara County residents to find programs like free school meals and groceries near them.">```. This helps with SEO.
- [ ] - Is the id `address-label` being used? If it isn't, remove it from the form label. 
- [ ] - See the current way I wrap the `<input>` element in `<label>` element. I do this to address accessibility. I recommend doing this so it doesn't get flagged by the Chrome Lighthouse audit later. Or, change your label's id so it matches the input element's id. 
- [ ] - I think the label should be "Enter Your Address:" not "Your Address"? 
- [ ] - The distance between the logos looks weird on tablet view. I think I expect the logos to be closer to each other. 

There may be other accessibility issues to address after this gets merged in (unfortunately we cannot run the Lighthouse audit tool until this is published live).

**Comment by danekolsen** [comment]
- [x] Can you update index.html so the new footer background colors are in sync with the current file? I darkened the color to address accessibility (the color previously provided on design doesn't meet WCAG AAA standards for high enough color contrast). FIXED

- [ ] Can you also add "results" next to the number (to match the user-friendly label revisions in Figma on the “Results” page) UPDATE NEEDED: This causes the test to wrap on small mobile screens. Shrinking the text small enough to fit will make it too small. @jliekim How should we handle this?

- [ ] In the Figma Results page it looks like the miles is not included. I understand how that may be important information, so maybe it could be a separate line underneath the Details or below the Address. "Distance From Your Address" might be the label? @jliekim thoughts?

- [x] The color contrast is not high enough for the current background of the Results. Change it to #006075. It will match the buttons in the footer. UPDATE NEEDED: My footer button color is just transparent white, so it changed when I altered the background color in the first todo. If we are trying to match the footer buttons and the top level results bg, I'll need one solid color to attach to both. UPDATE: Yan Yin wants #006075 on results headers and footer buttons. FIXED.

- [x] @jliekim will you be uploading the hi-res version of the watermark images in an issue, or directly into this branch > assets > img? UPDATE: New img uploaded. Dane added to files. FIXED.

- [x] Add .gitignore. Otherwise, .DS_Store will continue to be committed accidentally into the files. Inside gitignore please include .DS_Store, assets/img/.DS_Store and assets/.DS_Store. FIXED Added generic macOS gitignore from Github.

- [x] Add this back into index.html. It's already in the current file, but got removed in this branch: <meta name="Description" content="A lookup tool for Santa Clara County residents to find programs like free school meals and groceries near them.">. This helps with SEO. FIXED

- [x] Is the id address-label being used? If it isn't, remove it from the form label. YES, being used for styles.

- [x] See the current way I wrap the <input> element in <label> element. I do this to address accessibility. I recommend doing this so it doesn't get flagged by the Chrome Lighthouse audit later. Or, change your label's id so it matches the input element's id. FIXED by matching the ID

- [x] I think the label should be "Enter Your Address:" not "Your Address"? FIXED

- [x] The distance between the logos looks weird on tablet view. I think I expect the logos to be closer to each other. FIXED

**Comment by jliekim** [comment]
plate - 1200x1200

Requested image attached. 

I want to hold off on other concerns you have until we receive more feedback from Joel, the Mayor's office, or residents. Additional user testing could be helpful. This would be a good opportunity for a UI/UX/research person within Code for SJ to step into that role. 

Thanks so much!

**Pull request merged**
